
spring:
  data:
    rest:
      base-path:

rest:
  endpoint:
    fashion: "http://localhost:8082/bestseller/fashion"
    toys: "http://localhost:8081/bestseller/toys"
    hotdeals: "http://localhost:8083/deals/hot"
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8888