apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway-ingress
  namespace: shoppingdemo
spec:
  rules:
    - host: gateway-${HOSTPATTERN}.chaos.codecentric.io
      http:
        paths:
          - path: /
            backend:
              serviceName: gateway-service
              servicePort: 8080