apiVersion: v1
kind: Service
metadata:
  namespace: shoppingdemo
  name: fashion-service
  labels:
    app: shoppingdemo
spec:
  ports:
  - name: "http"
    port: 8082
    targetPort: 8082
  selector:
    app: fashion