apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shoppingdemo
  name: hotdeals-pod
  labels:
    app: shoppingdemo
    type: spring-boot
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: hotdeals
    spec:
      containers:
      - image: docker.io/mrbwilms/hot-deals:chaos-ws-k8s
        name: hotdeals
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        resources: {}
        livenessProbe:
          httpGet:
            port: 8083
            path: /actuator/health
          initialDelaySeconds: 30
          failureThreshold: 3
          timeoutSeconds: 5
      restartPolicy: Always
  selector:
    matchLabels:
      app: hotdeals
