apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shoppingdemo
  name: toys-pod
  labels:
    app: shoppingdemo
    type: spring-boot
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: toys
    spec:
      containers:
      - image: docker.io/mrbwilms/bestseller-toys:chaos-ws-k8s
        name: toys
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        resources: {}
        livenessProbe:
          httpGet:
            port: 8081
            path: /actuator/health
          initialDelaySeconds: 30
          failureThreshold: 3
          timeoutSeconds: 5
      restartPolicy: Always
  selector:
    matchLabels:
      app: toys
