# Manual a-priori configuration. Configuration will be only used when the sensor
# is actually installed by the agent.
# The commented out example values represent example configuration and are not
# necessarily defaults. Defaults are usually 'absent' or mentioned separately.
# Changes are hot reloaded unless otherwise mentioned.

# It is possible to create files called 'configuration-abc.yaml' which are
# merged with this file in file system order. So 'configuration-cde.yaml' comes
# after 'configuration-abc.yaml'. Only nested structures are merged, values are
# overwritten by subsequent configurations.

# Secrets
# To filter sensitive data from collection by the agent, all sensors respect
# the following secrets configuration. If a key collected by a sensor matches
# an entry from the list, the value is redacted.
#com.instana.secrets:
#  matcher: 'contains-ignore-case' # 'contains-ignore-case', 'contains', 'regex'
#  list:
#    - 'key'
#    - 'password'
#    - 'secret'

# Ignore processes
# To ignore any monitoring of certain processes, uncomment the
# com.instana.ignore section and list all process names of processes that should
# not be monitored.
# Sometimes scripts or other jobs are started through the same command, but
# only the execution of a single command should be ignored. In this case use
# arguments to specify any argument that should cause a process to be ignored.
#com.instana.ignore:
#  processes:
#    - 'java'
#    - 'httpd'
#  arguments:
#    - '-batch-file=/tmp/batch.def'

# Host
# Instana will by default only monitor local filesystems. It is possible to
# explicitly list the remote filesystems that shall be monitored.
# The name for the config setting is the device name, that is the first column
# in mtab / df
com.instana.plugin.host:
  tags:
  - 'shopping-chaos-demo'
#  filesystems:
#    - 'server:/usr/local/pub'

# Hardware & Zone
com.instana.plugin.generic.hardware:
  enabled: true # disabled by default
  availability-zone: 'shopping-chaos-demo'

# Apache Httpd
#com.instana.plugin.httpd:
#  user: ''
#  password: ''

# Custom processes
# To enable low level metric and availability monitoring for not automatically
# discovered processes, uncomment the com.instana.plugin.process section and
# list all process names of processes that should be monitored.
# Sometimes scripts or other jobs are started through the same command, but
# only the execution of a single command should be monitored. In this case use
# arguments to specify any argument that should cause a process to be monitored.
#com.instana.plugin.process:
#  processes:
#    - 'sshd'
#    - 'slapd'
#  arguments:
#    - '/opt/script.sh'

# Memcached
#com.instana.plugin.memcached:
#  user: ''
#  password: ''

# MongoDB
#com.instana.plugin.mongodb:
#  user: ''
#  source: '' # database where the user is defined
#  password: ''

# Mssql
#com.instana.plugin.mssql:
#  user: ''
#  password: ''

# Mysql
#com.instana.plugin.mysql:
#  user: ''
#  password: ''

# MariaDB
#com.instana.plugin.mariadb:
#  user: ''
#  password: ''

# PostgreSQL
#com.instana.plugin.postgresql:
#  user: ''
#  password: ''
#  database: '' # by default PostgreSQL will use 'user' as database to connect to.

# Redis
#com.instana.plugin.redis:
#  password: ''
#  Instana requires the CONFIG command. If it was renamed using 'rename-command'
#  this setting can be used to tell Instana the new name
#  config-command: 'CONFIG'
#  Monitor certain values in Redis
#  monitor:
#    - db: 0 # db number - defaults to 0 if absent
#      key: 'logstash' # key of value, given as string
#      type: 'list-length' # metric type. Currently only supports 'list-length'

# RabbitMq
#com.instana.plugin.rabbitmq:
#  user: 'guest'
#  password: 'guest'
#  monitorQueues:
#    - queue: queueName #name of the queue
#      vhost: / #name of the vhost, default is '/'

# OracleDB
#com.instana.plugin.oracledb:
#  password: ''
#  user: '' #default is 'sys as sysdba'
#  port: '' #default '1521'
#  host: '' #default is 'localhost'

# StatsD
#com.instana.plugin.statsd:
#  enabled: true # disabled by default
#  ports:
#    udp: 8125
#    mgmt: 8126
#  flush-interval: 10 # 10 seconds by default

# Sap HANA
#com.instana.plugin.saphana:
#  singleContainer:
#    user: '' #default is 'SYSTEM'
#    password: ''
#  multiContainer:
#    DATABASE_NAME_1: #example 'HXE'
#      user: '' #default is 'SYSTEM'
#      password: ''
#    DATABASE_NAME_2:
#      user: '' #default is 'SYSTEM'
#      password: ''

# Java & Custom JMX
#com.instana.plugin.java:
#  jmx:
#    # JMX is NOT hot-reloaded and needs to be set before a JVM is discovered.
#    # Supported attribute types are Number and Boolean
#    # delta calculation is only supported for Number
#    - object_name: 'java.lang:type=Compilation'
#      metrics:
#        - attributes: 'TotalCompilationTime'
#          type: 'delta' # delta will report the change to the previous second
#    - object_name: 'java.lang:type=ClassLoading'
#      metrics:
#        - attributes: 'LoadedClassCount'
#          type: 'absolute' # absolute will report the value as-is

# General Tracing Settings
#com.instana.tracing:
#  extra-http-headers:
#    # List of extra headers that should be captured by Instana.
#    # Will be matched using case-insensitive match.
#    - 'x-loadtest-id'

# Java Tracing
com.instana.plugin.javatrace:
  instrumentation:
    #    # Lightweight Bytecode Instrumentation, enabled by default
    #    # Disabling currently requires an agent restart
    enabled: true
    #    # OpenTracing instrumentation, disabled by default
    #    # Enabling requires an agent restart
    opentracing: false
#    # To enable using the SDK, provide a list of packages that should be
#    # scanned for SDK annotations. All subpackages are scanned, as it is a
#    # starts-with prefix matching.
#    # Scanning a large amount of classes slows down agent attach and requires
#    # more CPU for parsing, therefore it is recommended to limit to packages
#    # actually using SDK annotations.
#    # By default no packages are scanned for SDK annotations.
#    sdk:
#      packages:
#        - 'com.instana.backend'
#        - 'com.instana.frontend'